// <auto-generated />
using System;
using Hamburger.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hamburger.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230829131654_initdb")]
    partial class initdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hamburger.Models.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Hamburgers",
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7759),
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7771),
                            isActive = true
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Sides",
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7773),
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7773),
                            isActive = true
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Beverages",
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7774),
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7775),
                            isActive = true
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Deserts",
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7775),
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7776),
                            isActive = true
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Sauces",
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7776),
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7777),
                            isActive = true
                        });
                });

            modelBuilder.Entity("Hamburger.Models.Entities.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8298),
                            Description = "Whopper eti, büyük boy susamlı sandviç ekmeği, salatalık turşusu, ketçap, mayonez, doğranmış marul, domates ve soğandan oluşan bir Burger klasiği. Enfes patates kızartması ve içeceğiyle birlikte Whopper® Menü keyfini istediğin gibi yaşa!",
                            MenuImage = "https://www.burgerking.com.tr/cmsfiles/products/whopper-menu.png?v=285",
                            MenuName = "Whopper Menü",
                            Price = 189.99m,
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8299),
                            isActive = true
                        },
                        new
                        {
                            ID = 2,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8301),
                            Description = "Whopper® eti, büyük boy susamlı sandviç ekmeği, mayonez, doğranmış marul, soğan halkaları, nefis barbekü sosu ve cheddar peynirinden oluşan Whopper lezzeti. Enfes patates kızartması ve içeceğiyle birlikte Rodeo Whopper® Menü keyfini istediğin gibi yaşa!",
                            MenuImage = "https://www.burgerking.com.tr/cmsfiles/products/rodeo-whopper-menu.png?v=285",
                            MenuName = "Rodeo Whopper Menü",
                            Price = 189.99m,
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8301),
                            isActive = true
                        },
                        new
                        {
                            ID = 3,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8302),
                            Description = "Hamburger eti, küçük boy susamlı sandviç ekmeği, salatalık turşusu, ketçap, mayonez, doğranmış marul, domates ve soğandan oluşan, Whopper lezzetinden vazgeçemeyenlere nefis bir seçim. Enfes patates kızartması ve içeceğiyle birlikte Whopper Jr. Menü keyfini istediğin gibi yaşa!",
                            MenuImage = "https://www.burgerking.com.tr/cmsfiles/products/whopper-jr-menu.png?v=285",
                            MenuName = "Whopper Jr. Menü",
                            Price = 159.99m,
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8303),
                            isActive = true
                        },
                        new
                        {
                            ID = 4,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8304),
                            Description = "Fish Royale® eti, küçük boy susamlı sandviç ekmeği, doğranmış marul ve Burger klasiğine lezzetini veren tartar sosun birleşimi olan Fish Royale®, balık eti sevenlerin tercihi olacak. Enfes patates kızartması ve içeceği ile istediğin gibi yaşa!",
                            MenuImage = "https://www.burgerking.com.tr/cmsfiles/products/fish-royale-menu.png?v=285",
                            MenuName = "Fish Royale Menü",
                            Price = 169.99m,
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8304),
                            isActive = true
                        },
                        new
                        {
                            ID = 5,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8305),
                            Description = "King Chicken eti, susamlı sandviç ekmeği, mayonez ve doğranmış maruldan oluşan bu son derece sade alternatifi, enfes patates kızartması ve içeceğiyle birlikte istediğin gibi yaşa!",
                            MenuImage = "https://www.burgerking.com.tr/cmsfiles/products/king-chicken-menu.png?v=285",
                            MenuName = "King Chicken Menü",
                            Price = 169.99m,
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8305),
                            isActive = true
                        },
                        new
                        {
                            ID = 6,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8306),
                            Description = "Kocaman Steakhouse eti, özel sosu, cheddar peyniri, domatesi, mayonezi, marulu ve çıtır kaplamalı soğanlarıyla sabrınızı zorlayacak bir lezzet. Enfes patates kızartması ve içeceğiyle birlikte BK Steakhouse Burger® Menü keyfini istediğin gibi yaşa!",
                            MenuImage = "https://www.burgerking.com.tr/cmsfiles/products/bk-steakhouse-burger-menu.png?v=285",
                            MenuName = "Steakhouse Menü",
                            Price = 209.99m,
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8307),
                            isActive = true
                        },
                        new
                        {
                            ID = 7,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8307),
                            Description = "4 adet Hamburger eti, 3 katlı özel ekmeği, cheddar peyniri, salatalık turşusu, doğranmış marul ve soğana eşlik eden özel Big King sosun birleşimi. Enfes patates kızartması ve içeceğiyle birlikte Double Menü keyfini istediğin gibi yaşa",
                            MenuImage = "https://www.burgerking.com.tr/cmsfiles/products/double-big-king-menu.png?v=285",
                            MenuName = "Double King Menü",
                            Price = 219.99m,
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8308),
                            isActive = true
                        },
                        new
                        {
                            ID = 8,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8385),
                            Description = "İki adet Whopper eti, büyük boy susamlı sandviç ekmeği, salatalık turşusu, ketçap, mayonez, doğranmış marul, domates ve soğanla, klasik Whopper® lezzetini ikiye katlamak için ideal. Enfes patates kızartması ve içeceğiyle birlikte Double Whopper Menü keyfini istediğin gibi yaşa!",
                            MenuImage = "https://www.burgerking.com.tr/cmsfiles/products/double-whopper-menu.png?v=285",
                            MenuName = "Double Whopper Menü",
                            Price = 210.99m,
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8386),
                            isActive = true
                        },
                        new
                        {
                            ID = 9,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8387),
                            Description = "Özel kaplamasıyla tavuk göğüs fileto, mısır irmiği ile süslemeli özel ekmeği, spicy sosu, domatesi ve doğranmış maruldan oluşan yeni bir lezzet. Enfes patates kızartması ve içeceğiyle birlikte Spicy Gurme Tavuk Menü keyfini istediğin gibi yaşa!",
                            MenuImage = "https://www.burgerking.com.tr/cmsfiles/products/spicy-gurme-tavuk-menu.png?v=285",
                            MenuName = "Spicy Gurme Tavuk Menü",
                            Price = 170.99m,
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8388),
                            isActive = true
                        },
                        new
                        {
                            ID = 10,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8389),
                            Description = "2 adet Whopper eti, büyük boy susamlı sandviç ekmeği, salatalık turşusu, cheddar peyniri, hardal ve ketçaptan oluşan oluşan lezzet. Enfes patates kızartması ve içeceğiyle birlikte Mega Double Cheeseburger Menü keyfini istediğin gibi yaşa!",
                            MenuImage = "https://www.burgerking.com.tr/cmsfiles/products/mega-double-cheeseburger-menu.png?v=285",
                            MenuName = "Mega Double Cheeseburger Menü",
                            Price = 170.99m,
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8389),
                            isActive = true
                        },
                        new
                        {
                            ID = 11,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8390),
                            Description = "Enfes patates kızartması ve içeceğiyle birlikte 6'lı Nuggets Menü keyfini istediğin gibi yaşa!",
                            MenuImage = "https://www.burgerking.com.tr/cmsfiles/products/6li-bk-king-nuggets-menu.png?v=285",
                            MenuName = "6 lı Nuggets Menü",
                            Price = 100.99m,
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8390),
                            isActive = true
                        },
                        new
                        {
                            ID = 12,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8391),
                            Description = "Enfes patates kızartması ve içeceğiyle birlikte 6'lı Tenders Menü keyfini istediğin gibi yaşa!",
                            MenuImage = "https://www.burgerking.com.tr/cmsfiles/products/6li-chicken-tenders-menu-1.png?v=285",
                            MenuName = "6 lı Tenders Menü",
                            Price = 130.99m,
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8392),
                            isActive = true
                        });
                });

            modelBuilder.Entity("Hamburger.Models.Entities.MenuProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MenuID");

                    b.HasIndex("ProductID");

                    b.ToTable("MenuProducts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            MenuID = 1,
                            ProductID = 101
                        },
                        new
                        {
                            ID = 2,
                            MenuID = 1,
                            ProductID = 201
                        },
                        new
                        {
                            ID = 3,
                            MenuID = 1,
                            ProductID = 302
                        },
                        new
                        {
                            ID = 4,
                            MenuID = 2,
                            ProductID = 105
                        },
                        new
                        {
                            ID = 5,
                            MenuID = 2,
                            ProductID = 201
                        },
                        new
                        {
                            ID = 6,
                            MenuID = 2,
                            ProductID = 302
                        },
                        new
                        {
                            ID = 7,
                            MenuID = 3,
                            ProductID = 107
                        },
                        new
                        {
                            ID = 8,
                            MenuID = 3,
                            ProductID = 201
                        },
                        new
                        {
                            ID = 9,
                            MenuID = 3,
                            ProductID = 302
                        },
                        new
                        {
                            ID = 10,
                            MenuID = 4,
                            ProductID = 109
                        },
                        new
                        {
                            ID = 11,
                            MenuID = 4,
                            ProductID = 201
                        },
                        new
                        {
                            ID = 12,
                            MenuID = 4,
                            ProductID = 302
                        },
                        new
                        {
                            ID = 13,
                            MenuID = 5,
                            ProductID = 102
                        },
                        new
                        {
                            ID = 14,
                            MenuID = 5,
                            ProductID = 201
                        },
                        new
                        {
                            ID = 15,
                            MenuID = 5,
                            ProductID = 302
                        },
                        new
                        {
                            ID = 16,
                            MenuID = 6,
                            ProductID = 103
                        },
                        new
                        {
                            ID = 17,
                            MenuID = 6,
                            ProductID = 201
                        },
                        new
                        {
                            ID = 18,
                            MenuID = 6,
                            ProductID = 302
                        },
                        new
                        {
                            ID = 19,
                            MenuID = 7,
                            ProductID = 104
                        },
                        new
                        {
                            ID = 20,
                            MenuID = 7,
                            ProductID = 201
                        },
                        new
                        {
                            ID = 21,
                            MenuID = 7,
                            ProductID = 302
                        },
                        new
                        {
                            ID = 22,
                            MenuID = 8,
                            ProductID = 106
                        },
                        new
                        {
                            ID = 23,
                            MenuID = 8,
                            ProductID = 201
                        },
                        new
                        {
                            ID = 24,
                            MenuID = 8,
                            ProductID = 302
                        },
                        new
                        {
                            ID = 25,
                            MenuID = 9,
                            ProductID = 108
                        },
                        new
                        {
                            ID = 26,
                            MenuID = 9,
                            ProductID = 201
                        },
                        new
                        {
                            ID = 27,
                            MenuID = 9,
                            ProductID = 302
                        },
                        new
                        {
                            ID = 28,
                            MenuID = 10,
                            ProductID = 110
                        },
                        new
                        {
                            ID = 29,
                            MenuID = 10,
                            ProductID = 201
                        },
                        new
                        {
                            ID = 30,
                            MenuID = 10,
                            ProductID = 302
                        },
                        new
                        {
                            ID = 31,
                            MenuID = 11,
                            ProductID = 205
                        },
                        new
                        {
                            ID = 32,
                            MenuID = 11,
                            ProductID = 201
                        },
                        new
                        {
                            ID = 33,
                            MenuID = 11,
                            ProductID = 302
                        },
                        new
                        {
                            ID = 34,
                            MenuID = 12,
                            ProductID = 206
                        },
                        new
                        {
                            ID = 35,
                            MenuID = 12,
                            ProductID = 201
                        },
                        new
                        {
                            ID = 36,
                            MenuID = 12,
                            ProductID = 302
                        });
                });

            modelBuilder.Entity("Hamburger.Models.Entities.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Hamburger.Models.Entities.OrderDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("MenuID")
                        .HasColumnType("int");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SizeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MenuID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SizeID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Hamburger.Models.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 101,
                            CategoryID = 1,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7847),
                            Description = "Whopper® eti, büyük boy susamlı sandviç ekmeği, salatalık turşusu, ketçap, mayonez, doğranmış marul, domates ve soğandan oluşan bir Burger King® klasiği.",
                            Price = 134.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/whopper.png?v=285",
                            ProductName = "Whopper Burger",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7848),
                            isActive = true
                        },
                        new
                        {
                            ID = 102,
                            CategoryID = 1,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7911),
                            Description = "King Chicken eti, susamlı sandviç ekmeği, mayonez ve doğranmış maruldan oluşan son derece sade bir lezzet alternatifi.",
                            Price = 124.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/king-chicken-1.png?v=285",
                            ProductName = "King Chicken Burger",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7912),
                            isActive = true
                        },
                        new
                        {
                            ID = 103,
                            CategoryID = 1,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7916),
                            Description = "Kocaman Steakhouse eti, özel sosu, cheddar peyniri, domatesi, mayonezi, marulu ve çıtır kaplamalı soğanlarıyla sabrınızı zorlayacak bir lezzet.",
                            Price = 174.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/bk-steakhouse-burger.png?v=285",
                            ProductName = "Steakhouse Burger",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7916),
                            isActive = true
                        },
                        new
                        {
                            ID = 104,
                            CategoryID = 1,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7918),
                            Description = "4 adet Hamburger eti, 3 katlı özel ekmeği, cheddar peyniri, salatalık turşusu, doğranmış marul ve soğana eşlik eden özel Big King® sosun birleşimi",
                            Price = 184.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/double-big-king.png?v=285",
                            ProductName = "Double Big King Burger",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7918),
                            isActive = true
                        },
                        new
                        {
                            ID = 105,
                            CategoryID = 1,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7920),
                            Description = "Whopper® eti, büyük boy susamlı sandviç ekmeği, mayonez, doğranmış marul, soğan halkaları, nefis barbekü sosu ve 2 adet cheddar peynirinden oluşan Whopper® lezzeti.",
                            Price = 159.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/rodeo-whopper.png?v=285",
                            ProductName = "Rodeo Whopper Burger",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7920),
                            isActive = true
                        },
                        new
                        {
                            ID = 106,
                            CategoryID = 1,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7922),
                            Description = "İki adet Whopper® eti, büyük boy susamlı sandviç ekmeği, salatalık turşusu, ketçap, mayonez, doğranmış marul, domates ve soğanla klasik Whopper® lezzetini ikiye katlamak için ideal.",
                            Price = 194.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/double-whopper-1.png?v=285",
                            ProductName = "Double Whopper Burger",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7922),
                            isActive = true
                        },
                        new
                        {
                            ID = 107,
                            CategoryID = 1,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7925),
                            Description = "Hamburger eti, küçük boy susamlı sandviç ekmeği, salatalık turşusu, ketçap, mayonez, doğranmış marul, domates ve soğandan oluşan, Whopper® lezzetinden vazgeçemeyenlere nefis bir seçim.",
                            Price = 119.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/whopper-jr.png?v=285",
                            ProductName = "Whopper Jr. Burger",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7925),
                            isActive = true
                        },
                        new
                        {
                            ID = 108,
                            CategoryID = 1,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7927),
                            Description = "Özel kaplamasıyla tavuk göğüs fileto, mısır irmiği ile süslemeli özel ekmeği, spicy sosu, domatesi ve doğranmış maruldan oluşan yeni bir lezzet.",
                            Price = 129.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/spicy-gurme-tavuk.png?v=285",
                            ProductName = "Spicy Gurme Burger",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7927),
                            isActive = true
                        },
                        new
                        {
                            ID = 109,
                            CategoryID = 1,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7929),
                            Description = "Fish Royale® eti, küçük boy susamlı sandviç ekmeği, doğranmış marul ile burger klasiğine lezzetini veren tartar sosun birleşimi.",
                            Price = 159.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/fish-royale-1.png?v=285",
                            ProductName = "Fish Royale Burger",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7930),
                            isActive = true
                        },
                        new
                        {
                            ID = 110,
                            CategoryID = 1,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7931),
                            Description = "2 adet Whopper® eti, büyük boy susamlı sandviç ekmeği, salatalık turşusu, 4 adet cheddar peyniri, hardal ve ketçaptan oluşan lezzet.",
                            Price = 159.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/mega-double-cheeseburger.png?v=285",
                            ProductName = "Mega Double CheeseBurger",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7932),
                            isActive = true
                        },
                        new
                        {
                            ID = 201,
                            CategoryID = 2,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7933),
                            Description = "Doğal, soyulmuş, gevrek kızarmış patates",
                            Price = 59.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/patates.png?v=285",
                            ProductName = "Patates",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7934),
                            isActive = true
                        },
                        new
                        {
                            ID = 202,
                            CategoryID = 2,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7935),
                            Description = "Çıtır Mı Çıtır Altın Sarısı Tırtıklı Patates",
                            Price = 69.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/tirtikli-patates.png?v=285",
                            ProductName = "Tırtıklı  Patates",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7936),
                            isActive = true
                        },
                        new
                        {
                            ID = 203,
                            CategoryID = 2,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7937),
                            Description = "Çıtır çıtır 8’li, 12’li ya da 16’lı Soğan Halka lezzeti",
                            Price = 79.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/sogan-halkasi.png?v=285",
                            ProductName = "Soğan Halkası",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7938),
                            isActive = true
                        },
                        new
                        {
                            ID = 204,
                            CategoryID = 2,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7939),
                            Description = "Dışı çıtır çıtır, içi sıcacık peyniriyle Çıtır Peynir!",
                            Price = 75.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/citir-peynir.png?v=285",
                            ProductName = "Çıtır Peynir",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7940),
                            isActive = true
                        },
                        new
                        {
                            ID = 205,
                            CategoryID = 2,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7941),
                            Description = "Dışı çıtır çıtır Nuggets...",
                            Price = 75.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/bk-king-nuggets-1.png?v=285",
                            ProductName = "Çıtır Nuggets",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7942),
                            isActive = true
                        },
                        new
                        {
                            ID = 206,
                            CategoryID = 2,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7944),
                            Description = "Özel harcıyla nar gibi kızarmış  beyaz tavuk eti.",
                            Price = 85.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/chicken-tenders.png?v=285",
                            ProductName = "Çıtır Tavuk Tenders",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7945),
                            isActive = true
                        },
                        new
                        {
                            ID = 301,
                            CategoryID = 3,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7946),
                            Description = "Şeftalili Fuse Tea ve Limonlu Fuse Tea seçenekleri ile",
                            Price = 35.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/fuse-tea.png?v=285",
                            ProductName = "Fuse Tea",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7947),
                            isActive = true
                        },
                        new
                        {
                            ID = 302,
                            CategoryID = 3,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7949),
                            Description = "Cola cola ",
                            Price = 35.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/coca-cola.png?v=285",
                            ProductName = "Coca Cola",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7949),
                            isActive = true
                        },
                        new
                        {
                            ID = 303,
                            CategoryID = 3,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7951),
                            Description = "Cola cola Zero ",
                            Price = 35.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/coca-cola-zero-sugar.png?v=285",
                            ProductName = "Coca Cola Zero",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7951),
                            isActive = true
                        },
                        new
                        {
                            ID = 304,
                            CategoryID = 3,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7953),
                            Description = "Fanta",
                            Price = 35.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/fanta.png?v=285",
                            ProductName = "Fanta",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7953),
                            isActive = true
                        },
                        new
                        {
                            ID = 305,
                            CategoryID = 3,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7955),
                            Description = "Sprite",
                            Price = 35.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/sprite.png?v=285",
                            ProductName = "Sprite",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7955),
                            isActive = true
                        },
                        new
                        {
                            ID = 306,
                            CategoryID = 3,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7957),
                            Description = "Ayran",
                            Price = 35.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/ayran-300-ml.png?v=285",
                            ProductName = "Ayran",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7958),
                            isActive = true
                        },
                        new
                        {
                            ID = 307,
                            CategoryID = 3,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7959),
                            Description = "Elma Suyu",
                            Price = 35.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/elma-suyu.png?v=285",
                            ProductName = "Cappy Elma Suyu",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7960),
                            isActive = true
                        },
                        new
                        {
                            ID = 308,
                            CategoryID = 3,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7961),
                            Description = "Atom Suyu",
                            Price = 35.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/cappy-atom-200-ml.png?v=285",
                            ProductName = "Cappy Atom",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7962),
                            isActive = true
                        },
                        new
                        {
                            ID = 309,
                            CategoryID = 3,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7963),
                            Description = "Kahve Lezzeti",
                            Price = 35.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/espresso.png?v=285",
                            ProductName = "Espresso",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7964),
                            isActive = true
                        },
                        new
                        {
                            ID = 310,
                            CategoryID = 3,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7965),
                            Description = "Kahve Lezzeti",
                            Price = 35.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/nescafe-black.png?v=285",
                            ProductName = "Filtre Kahve",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7966),
                            isActive = true
                        },
                        new
                        {
                            ID = 311,
                            CategoryID = 3,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7967),
                            Description = "Karadeniz Lezzeti",
                            Price = 35.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/cay.png?v=285",
                            ProductName = "Çay",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7968),
                            isActive = true
                        },
                        new
                        {
                            ID = 312,
                            CategoryID = 3,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7969),
                            Description = "Karadeniz Lezzeti",
                            Price = 35.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/vanilyali-cappuccino.png?v=285",
                            ProductName = "Cappuccino",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7970),
                            isActive = true
                        },
                        new
                        {
                            ID = 313,
                            CategoryID = 3,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7972),
                            Description = "Çikolata Lezzeti",
                            Price = 35.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/nestle-sicak-cikolata.png?v=285",
                            ProductName = "Sıcak Çikolata",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7973),
                            isActive = true
                        },
                        new
                        {
                            ID = 401,
                            CategoryID = 4,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7975),
                            Description = "Çikolata Lezzeti",
                            Price = 45.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/cikolatali-cookie.png?v=285",
                            ProductName = "Çikolatalı Cookie",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7975),
                            isActive = true
                        },
                        new
                        {
                            ID = 402,
                            CategoryID = 4,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7977),
                            Description = "Çikolata Lezzeti",
                            Price = 45.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/sufle.png?v=285",
                            ProductName = "Sufle",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7977),
                            isActive = true
                        },
                        new
                        {
                            ID = 403,
                            CategoryID = 4,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7979),
                            Description = "Vişne Lezzeti",
                            Price = 55.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/visneli-tatli.png?v=285",
                            ProductName = "Vişneli Tatlı",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7980),
                            isActive = true
                        },
                        new
                        {
                            ID = 404,
                            CategoryID = 4,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7981),
                            Description = "Vanilyalı, Çilekli, Çikolatalı, Espressolu, Limonlu çeşitleriyle.",
                            Price = 55.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/espressolu-milkshake.png?v=285",
                            ProductName = "Vişneli Tatlı",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7982),
                            isActive = true
                        },
                        new
                        {
                            ID = 405,
                            CategoryID = 4,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7984),
                            Description = "Vanilyalı, Çilekli, Çikolatalı, Espressolu, Limonlu çeşitleriyle.",
                            Price = 55.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/espressolu-milkshake.png?v=285",
                            ProductName = "Vişneli Tatlı",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7984),
                            isActive = true
                        },
                        new
                        {
                            ID = 406,
                            CategoryID = 4,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7987),
                            Description = "Vanilyalı, Çikolata Soslu, Böğürtlen Soslu, Karamel Soslu, Çilek Soslu, Limonlu",
                            Price = 65.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/king-sundae.png?v=285",
                            ProductName = "King Sundae",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7987),
                            isActive = true
                        },
                        new
                        {
                            ID = 407,
                            CategoryID = 4,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7989),
                            Description = "Çikolata Parçacıklı, Renkli Çikolata Drajeleri, Limonlu",
                            Price = 75.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/bkool.png?v=285",
                            ProductName = "Bkool",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7989),
                            isActive = true
                        },
                        new
                        {
                            ID = 501,
                            CategoryID = 5,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7991),
                            Description = "Acı Sos",
                            Price = 10.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/mini-aci-sos.png?v=285",
                            ProductName = "Mini Acı Sos",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7991),
                            isActive = true
                        },
                        new
                        {
                            ID = 502,
                            CategoryID = 5,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7993),
                            Description = "Mayonez",
                            Price = 10.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/mini-mayonez.png?v=285",
                            ProductName = "Mayonez",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7993),
                            isActive = true
                        },
                        new
                        {
                            ID = 503,
                            CategoryID = 5,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7995),
                            Description = "Ranch Sos",
                            Price = 10.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/mini-ranch.png?v=285",
                            ProductName = "Mini Ranch",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7996),
                            isActive = true
                        },
                        new
                        {
                            ID = 504,
                            CategoryID = 5,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7997),
                            Description = "Sarımsaklı Sos",
                            Price = 10.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/mini-sarimsakli-mayonez-1.png?v=285",
                            ProductName = "Sarımsaklı Sos",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7998),
                            isActive = true
                        },
                        new
                        {
                            ID = 505,
                            CategoryID = 5,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(7999),
                            Description = "Mini Ketçap",
                            Price = 10.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/mini-ketcap.png?v=285",
                            ProductName = "Mini Ketçap",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8000),
                            isActive = true
                        },
                        new
                        {
                            ID = 506,
                            CategoryID = 5,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8001),
                            Description = "Buffalo Sos",
                            Price = 10.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/mini-buffalo-1.png?v=285",
                            ProductName = "Buffalo Sos",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8002),
                            isActive = true
                        },
                        new
                        {
                            ID = 507,
                            CategoryID = 5,
                            CreateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8003),
                            Description = "Mini BBQ",
                            Price = 10.99m,
                            ProductImage = "https://www.burgerking.com.tr/cmsfiles/products/mini-bbq.png?v=285",
                            ProductName = "Mini BBQ",
                            UpdateDate = new DateTime(2023, 8, 29, 16, 16, 53, 649, DateTimeKind.Local).AddTicks(8004),
                            isActive = true
                        });
                });

            modelBuilder.Entity("Hamburger.Models.Entities.ProductTopping", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("ToppingID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("ToppingID");

                    b.ToTable("ProductToppings");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ProductID = 101,
                            ToppingID = 1
                        },
                        new
                        {
                            ID = 2,
                            ProductID = 101,
                            ToppingID = 2
                        },
                        new
                        {
                            ID = 3,
                            ProductID = 101,
                            ToppingID = 3
                        },
                        new
                        {
                            ID = 4,
                            ProductID = 101,
                            ToppingID = 4
                        },
                        new
                        {
                            ID = 5,
                            ProductID = 101,
                            ToppingID = 8
                        },
                        new
                        {
                            ID = 6,
                            ProductID = 101,
                            ToppingID = 9
                        },
                        new
                        {
                            ID = 7,
                            ProductID = 102,
                            ToppingID = 4
                        },
                        new
                        {
                            ID = 8,
                            ProductID = 102,
                            ToppingID = 9
                        },
                        new
                        {
                            ID = 9,
                            ProductID = 103,
                            ToppingID = 1
                        },
                        new
                        {
                            ID = 10,
                            ProductID = 103,
                            ToppingID = 9
                        },
                        new
                        {
                            ID = 11,
                            ProductID = 103,
                            ToppingID = 5
                        },
                        new
                        {
                            ID = 12,
                            ProductID = 103,
                            ToppingID = 4
                        },
                        new
                        {
                            ID = 13,
                            ProductID = 103,
                            ToppingID = 7
                        },
                        new
                        {
                            ID = 14,
                            ProductID = 103,
                            ToppingID = 10
                        },
                        new
                        {
                            ID = 15,
                            ProductID = 104,
                            ToppingID = 5
                        },
                        new
                        {
                            ID = 16,
                            ProductID = 104,
                            ToppingID = 2
                        },
                        new
                        {
                            ID = 17,
                            ProductID = 104,
                            ToppingID = 4
                        },
                        new
                        {
                            ID = 18,
                            ProductID = 104,
                            ToppingID = 3
                        },
                        new
                        {
                            ID = 19,
                            ProductID = 104,
                            ToppingID = 11
                        },
                        new
                        {
                            ID = 20,
                            ProductID = 105,
                            ToppingID = 4
                        },
                        new
                        {
                            ID = 21,
                            ProductID = 105,
                            ToppingID = 9
                        },
                        new
                        {
                            ID = 22,
                            ProductID = 105,
                            ToppingID = 12
                        },
                        new
                        {
                            ID = 23,
                            ProductID = 105,
                            ToppingID = 13
                        },
                        new
                        {
                            ID = 24,
                            ProductID = 105,
                            ToppingID = 5
                        },
                        new
                        {
                            ID = 25,
                            ProductID = 106,
                            ToppingID = 2
                        },
                        new
                        {
                            ID = 26,
                            ProductID = 106,
                            ToppingID = 8
                        },
                        new
                        {
                            ID = 27,
                            ProductID = 106,
                            ToppingID = 9
                        },
                        new
                        {
                            ID = 28,
                            ProductID = 106,
                            ToppingID = 4
                        },
                        new
                        {
                            ID = 29,
                            ProductID = 106,
                            ToppingID = 1
                        },
                        new
                        {
                            ID = 30,
                            ProductID = 106,
                            ToppingID = 3
                        },
                        new
                        {
                            ID = 31,
                            ProductID = 107,
                            ToppingID = 2
                        },
                        new
                        {
                            ID = 32,
                            ProductID = 107,
                            ToppingID = 8
                        },
                        new
                        {
                            ID = 33,
                            ProductID = 107,
                            ToppingID = 9
                        },
                        new
                        {
                            ID = 34,
                            ProductID = 107,
                            ToppingID = 4
                        },
                        new
                        {
                            ID = 35,
                            ProductID = 107,
                            ToppingID = 1
                        },
                        new
                        {
                            ID = 36,
                            ProductID = 107,
                            ToppingID = 3
                        },
                        new
                        {
                            ID = 37,
                            ProductID = 108,
                            ToppingID = 1
                        },
                        new
                        {
                            ID = 38,
                            ProductID = 108,
                            ToppingID = 14
                        },
                        new
                        {
                            ID = 39,
                            ProductID = 108,
                            ToppingID = 4
                        },
                        new
                        {
                            ID = 40,
                            ProductID = 109,
                            ToppingID = 4
                        },
                        new
                        {
                            ID = 41,
                            ProductID = 109,
                            ToppingID = 15
                        },
                        new
                        {
                            ID = 42,
                            ProductID = 110,
                            ToppingID = 2
                        },
                        new
                        {
                            ID = 43,
                            ProductID = 110,
                            ToppingID = 16
                        },
                        new
                        {
                            ID = 44,
                            ProductID = 110,
                            ToppingID = 5
                        },
                        new
                        {
                            ID = 45,
                            ProductID = 110,
                            ToppingID = 8
                        });
                });

            modelBuilder.Entity("Hamburger.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "0bdc9376-f32d-45f7-8a07-ea7e49dc0f4b",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "616c9c1a-b095-4562-80e0-49f6988e8849",
                            Name = "Standard",
                            NormalizedName = "STANDARD"
                        });
                });

            modelBuilder.Entity("Hamburger.Models.Entities.Size", b =>
                {
                    b.Property<int>("SizeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeID"), 1L, 1);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SizeID");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            SizeID = 1,
                            Price = 0m,
                            SizeName = "Küçük Boy"
                        },
                        new
                        {
                            SizeID = 2,
                            Price = 0m,
                            SizeName = "Orta Boy"
                        },
                        new
                        {
                            SizeID = 3,
                            Price = 0m,
                            SizeName = "Büyük Boy"
                        });
                });

            modelBuilder.Entity("Hamburger.Models.Entities.Status", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"), 1L, 1);

                    b.Property<string>("StatusDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusID");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("Hamburger.Models.Entities.Topping", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ToppingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Toppings");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Price = 4.99m,
                            ToppingName = "Domates"
                        },
                        new
                        {
                            ID = 2,
                            Price = 5.99m,
                            ToppingName = "Salatalık Turşusu"
                        },
                        new
                        {
                            ID = 3,
                            Price = 3.99m,
                            ToppingName = "Soğan"
                        },
                        new
                        {
                            ID = 4,
                            Price = 2.99m,
                            ToppingName = "Marul"
                        },
                        new
                        {
                            ID = 5,
                            Price = 6.99m,
                            ToppingName = "Cheddar Peyniri"
                        },
                        new
                        {
                            ID = 6,
                            Price = 7.99m,
                            ToppingName = "Trüf Mantarı"
                        },
                        new
                        {
                            ID = 7,
                            Price = 5.99m,
                            ToppingName = "Çıtır Soğan"
                        },
                        new
                        {
                            ID = 8,
                            Price = 1.99m,
                            ToppingName = "Ketçap"
                        },
                        new
                        {
                            ID = 9,
                            Price = 1.99m,
                            ToppingName = "Mayonez"
                        },
                        new
                        {
                            ID = 10,
                            Price = 1.99m,
                            ToppingName = "Steakhouse Burger Sos"
                        },
                        new
                        {
                            ID = 11,
                            Price = 1.99m,
                            ToppingName = "BigKing Burger Sos"
                        },
                        new
                        {
                            ID = 12,
                            Price = 3.99m,
                            ToppingName = "Soğan Halkaları"
                        },
                        new
                        {
                            ID = 13,
                            Price = 2.99m,
                            ToppingName = "Barbekü Sos"
                        },
                        new
                        {
                            ID = 14,
                            Price = 2.99m,
                            ToppingName = "Spicy Sos"
                        },
                        new
                        {
                            ID = 15,
                            Price = 2.99m,
                            ToppingName = "Tartar Sos"
                        },
                        new
                        {
                            ID = 16,
                            Price = 2.99m,
                            ToppingName = "Hardal Sos"
                        });
                });

            modelBuilder.Entity("Hamburger.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Address = "Kadikoy",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "f52ab59b-768f-4133-8601-fa3adc21ef6e",
                            Email = "overthinkerst@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "overthinkers",
                            LastName = "team",
                            LockoutEnabled = false,
                            NormalizedEmail = "OVERTHINKERST@GMAIL.COM",
                            NormalizedUserName = "OVERTHINKERS",
                            PasswordHash = "AQAAAAEAACcQAAAAENJMmW7TYOiizCD7fUq1QlK8/r6iyOM4jiSNWHGuEeTLvNAICoMlM2AkdIRDmL3cVg==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "overthinkers"
                        });
                });

            modelBuilder.Entity("Hamburger.Models.Entities.UserFavorites", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("MenuID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Hamburger.Models.Entities.MenuProduct", b =>
                {
                    b.HasOne("Hamburger.Models.Entities.Menu", "Menu")
                        .WithMany("MenuProducts")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hamburger.Models.Entities.Product", "Product")
                        .WithMany("MenuProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Hamburger.Models.Entities.Order", b =>
                {
                    b.HasOne("Hamburger.Models.Entities.Status", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusID");

                    b.HasOne("Hamburger.Models.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hamburger.Models.Entities.OrderDetails", b =>
                {
                    b.HasOne("Hamburger.Models.Entities.Menu", "Menu")
                        .WithMany("OrderDetails")
                        .HasForeignKey("MenuID");

                    b.HasOne("Hamburger.Models.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID");

                    b.HasOne("Hamburger.Models.Entities.Product", "Products")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID");

                    b.HasOne("Hamburger.Models.Entities.Size", "Size")
                        .WithMany("OrderDetails")
                        .HasForeignKey("SizeID");

                    b.Navigation("Menu");

                    b.Navigation("Order");

                    b.Navigation("Products");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("Hamburger.Models.Entities.Product", b =>
                {
                    b.HasOne("Hamburger.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Hamburger.Models.Entities.ProductTopping", b =>
                {
                    b.HasOne("Hamburger.Models.Entities.Product", "Product")
                        .WithMany("ProductToppings")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hamburger.Models.Entities.Topping", "Topping")
                        .WithMany("ProductToppings")
                        .HasForeignKey("ToppingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("Hamburger.Models.Entities.UserFavorites", b =>
                {
                    b.HasOne("Hamburger.Models.Entities.Menu", "Menu")
                        .WithMany("UserFavorites")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hamburger.Models.Entities.Product", "Product")
                        .WithMany("UserFavorites")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hamburger.Models.Entities.User", "User")
                        .WithMany("UserFavorites")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Hamburger.Models.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Hamburger.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Hamburger.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Hamburger.Models.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hamburger.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Hamburger.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hamburger.Models.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Hamburger.Models.Entities.Menu", b =>
                {
                    b.Navigation("MenuProducts");

                    b.Navigation("OrderDetails");

                    b.Navigation("UserFavorites");
                });

            modelBuilder.Entity("Hamburger.Models.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Hamburger.Models.Entities.Product", b =>
                {
                    b.Navigation("MenuProducts");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductToppings");

                    b.Navigation("UserFavorites");
                });

            modelBuilder.Entity("Hamburger.Models.Entities.Size", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Hamburger.Models.Entities.Status", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Hamburger.Models.Entities.Topping", b =>
                {
                    b.Navigation("ProductToppings");
                });

            modelBuilder.Entity("Hamburger.Models.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserFavorites");
                });
#pragma warning restore 612, 618
        }
    }
}
